// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.dapper.rpc.serializer.protobuf;

public final class PersonFactory {
  private PersonFactory() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 age = 3;</code>
     */
    int getAge();

    /**
     * <code>optional .Addr addr = 4;</code>
     */
    boolean hasAddr();
    /**
     * <code>optional .Addr addr = 4;</code>
     */
    com.dapper.rpc.serializer.protobuf.PersonFactory.Addr getAddr();
    /**
     * <code>optional .Addr addr = 4;</code>
     */
    com.dapper.rpc.serializer.protobuf.PersonFactory.AddrOrBuilder getAddrOrBuilder();
  }
  /**
   * Protobuf type {@code Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      id_ = 0;
      name_ = "";
      age_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              age_ = input.readInt32();
              break;
            }
            case 34: {
              com.dapper.rpc.serializer.protobuf.PersonFactory.Addr.Builder subBuilder = null;
              if (addr_ != null) {
                subBuilder = addr_.toBuilder();
              }
              addr_ = input.readMessage(com.dapper.rpc.serializer.protobuf.PersonFactory.Addr.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(addr_);
                addr_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dapper.rpc.serializer.protobuf.PersonFactory.internal_static_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dapper.rpc.serializer.protobuf.PersonFactory.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dapper.rpc.serializer.protobuf.PersonFactory.Person.class, com.dapper.rpc.serializer.protobuf.PersonFactory.Person.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <code>optional int32 age = 3;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int ADDR_FIELD_NUMBER = 4;
    private com.dapper.rpc.serializer.protobuf.PersonFactory.Addr addr_;
    /**
     * <code>optional .Addr addr = 4;</code>
     */
    public boolean hasAddr() {
      return addr_ != null;
    }
    /**
     * <code>optional .Addr addr = 4;</code>
     */
    public com.dapper.rpc.serializer.protobuf.PersonFactory.Addr getAddr() {
      return addr_ == null ? com.dapper.rpc.serializer.protobuf.PersonFactory.Addr.getDefaultInstance() : addr_;
    }
    /**
     * <code>optional .Addr addr = 4;</code>
     */
    public com.dapper.rpc.serializer.protobuf.PersonFactory.AddrOrBuilder getAddrOrBuilder() {
      return getAddr();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (age_ != 0) {
        output.writeInt32(3, age_);
      }
      if (addr_ != null) {
        output.writeMessage(4, getAddr());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      if (addr_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getAddr());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dapper.rpc.serializer.protobuf.PersonFactory.Person)) {
        return super.equals(obj);
      }
      com.dapper.rpc.serializer.protobuf.PersonFactory.Person other = (com.dapper.rpc.serializer.protobuf.PersonFactory.Person) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && (getAge()
          == other.getAge());
      result = result && (hasAddr() == other.hasAddr());
      if (hasAddr()) {
        result = result && getAddr()
            .equals(other.getAddr());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      if (hasAddr()) {
        hash = (37 * hash) + ADDR_FIELD_NUMBER;
        hash = (53 * hash) + getAddr().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dapper.rpc.serializer.protobuf.PersonFactory.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dapper.rpc.serializer.protobuf.PersonFactory.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dapper.rpc.serializer.protobuf.PersonFactory.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dapper.rpc.serializer.protobuf.PersonFactory.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dapper.rpc.serializer.protobuf.PersonFactory.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dapper.rpc.serializer.protobuf.PersonFactory.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dapper.rpc.serializer.protobuf.PersonFactory.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dapper.rpc.serializer.protobuf.PersonFactory.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dapper.rpc.serializer.protobuf.PersonFactory.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dapper.rpc.serializer.protobuf.PersonFactory.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dapper.rpc.serializer.protobuf.PersonFactory.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        com.dapper.rpc.serializer.protobuf.PersonFactory.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dapper.rpc.serializer.protobuf.PersonFactory.internal_static_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dapper.rpc.serializer.protobuf.PersonFactory.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dapper.rpc.serializer.protobuf.PersonFactory.Person.class, com.dapper.rpc.serializer.protobuf.PersonFactory.Person.Builder.class);
      }

      // Construct using com.dapper.rpc.serializer.proto.PersonFactory.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        age_ = 0;

        if (addrBuilder_ == null) {
          addr_ = null;
        } else {
          addr_ = null;
          addrBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dapper.rpc.serializer.protobuf.PersonFactory.internal_static_Person_descriptor;
      }

      public com.dapper.rpc.serializer.protobuf.PersonFactory.Person getDefaultInstanceForType() {
        return com.dapper.rpc.serializer.protobuf.PersonFactory.Person.getDefaultInstance();
      }

      public com.dapper.rpc.serializer.protobuf.PersonFactory.Person build() {
        com.dapper.rpc.serializer.protobuf.PersonFactory.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dapper.rpc.serializer.protobuf.PersonFactory.Person buildPartial() {
        com.dapper.rpc.serializer.protobuf.PersonFactory.Person result = new com.dapper.rpc.serializer.protobuf.PersonFactory.Person(this);
        result.id_ = id_;
        result.name_ = name_;
        result.age_ = age_;
        if (addrBuilder_ == null) {
          result.addr_ = addr_;
        } else {
          result.addr_ = addrBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dapper.rpc.serializer.protobuf.PersonFactory.Person) {
          return mergeFrom((com.dapper.rpc.serializer.protobuf.PersonFactory.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dapper.rpc.serializer.protobuf.PersonFactory.Person other) {
        if (other == com.dapper.rpc.serializer.protobuf.PersonFactory.Person.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.hasAddr()) {
          mergeAddr(other.getAddr());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dapper.rpc.serializer.protobuf.PersonFactory.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dapper.rpc.serializer.protobuf.PersonFactory.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 3;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 3;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 3;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private com.dapper.rpc.serializer.protobuf.PersonFactory.Addr addr_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dapper.rpc.serializer.protobuf.PersonFactory.Addr, com.dapper.rpc.serializer.protobuf.PersonFactory.Addr.Builder, com.dapper.rpc.serializer.protobuf.PersonFactory.AddrOrBuilder> addrBuilder_;
      /**
       * <code>optional .Addr addr = 4;</code>
       */
      public boolean hasAddr() {
        return addrBuilder_ != null || addr_ != null;
      }
      /**
       * <code>optional .Addr addr = 4;</code>
       */
      public com.dapper.rpc.serializer.protobuf.PersonFactory.Addr getAddr() {
        if (addrBuilder_ == null) {
          return addr_ == null ? com.dapper.rpc.serializer.protobuf.PersonFactory.Addr.getDefaultInstance() : addr_;
        } else {
          return addrBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Addr addr = 4;</code>
       */
      public Builder setAddr(com.dapper.rpc.serializer.protobuf.PersonFactory.Addr value) {
        if (addrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          addr_ = value;
          onChanged();
        } else {
          addrBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Addr addr = 4;</code>
       */
      public Builder setAddr(
          com.dapper.rpc.serializer.protobuf.PersonFactory.Addr.Builder builderForValue) {
        if (addrBuilder_ == null) {
          addr_ = builderForValue.build();
          onChanged();
        } else {
          addrBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Addr addr = 4;</code>
       */
      public Builder mergeAddr(com.dapper.rpc.serializer.protobuf.PersonFactory.Addr value) {
        if (addrBuilder_ == null) {
          if (addr_ != null) {
            addr_ =
              com.dapper.rpc.serializer.protobuf.PersonFactory.Addr.newBuilder(addr_).mergeFrom(value).buildPartial();
          } else {
            addr_ = value;
          }
          onChanged();
        } else {
          addrBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Addr addr = 4;</code>
       */
      public Builder clearAddr() {
        if (addrBuilder_ == null) {
          addr_ = null;
          onChanged();
        } else {
          addr_ = null;
          addrBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Addr addr = 4;</code>
       */
      public com.dapper.rpc.serializer.protobuf.PersonFactory.Addr.Builder getAddrBuilder() {
        
        onChanged();
        return getAddrFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Addr addr = 4;</code>
       */
      public com.dapper.rpc.serializer.protobuf.PersonFactory.AddrOrBuilder getAddrOrBuilder() {
        if (addrBuilder_ != null) {
          return addrBuilder_.getMessageOrBuilder();
        } else {
          return addr_ == null ?
              com.dapper.rpc.serializer.protobuf.PersonFactory.Addr.getDefaultInstance() : addr_;
        }
      }
      /**
       * <code>optional .Addr addr = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dapper.rpc.serializer.protobuf.PersonFactory.Addr, com.dapper.rpc.serializer.protobuf.PersonFactory.Addr.Builder, com.dapper.rpc.serializer.protobuf.PersonFactory.AddrOrBuilder>
          getAddrFieldBuilder() {
        if (addrBuilder_ == null) {
          addrBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.dapper.rpc.serializer.protobuf.PersonFactory.Addr, com.dapper.rpc.serializer.protobuf.PersonFactory.Addr.Builder, com.dapper.rpc.serializer.protobuf.PersonFactory.AddrOrBuilder>(
                  getAddr(),
                  getParentForChildren(),
                  isClean());
          addr_ = null;
        }
        return addrBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Person)
    }

    // @@protoc_insertion_point(class_scope:Person)
    private static final com.dapper.rpc.serializer.protobuf.PersonFactory.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dapper.rpc.serializer.protobuf.PersonFactory.Person();
    }

    public static com.dapper.rpc.serializer.protobuf.PersonFactory.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    public com.dapper.rpc.serializer.protobuf.PersonFactory.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddrOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Addr)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string contry = 1;</code>
     */
    java.lang.String getContry();
    /**
     * <code>optional string contry = 1;</code>
     */
    com.google.protobuf.ByteString
        getContryBytes();

    /**
     * <code>optional string city = 2;</code>
     */
    java.lang.String getCity();
    /**
     * <code>optional string city = 2;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();
  }
  /**
   * Protobuf type {@code Addr}
   */
  public  static final class Addr extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Addr)
      AddrOrBuilder {
    // Use Addr.newBuilder() to construct.
    private Addr(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Addr() {
      contry_ = "";
      city_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Addr(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              contry_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              city_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dapper.rpc.serializer.protobuf.PersonFactory.internal_static_Addr_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dapper.rpc.serializer.protobuf.PersonFactory.internal_static_Addr_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dapper.rpc.serializer.protobuf.PersonFactory.Addr.class, com.dapper.rpc.serializer.protobuf.PersonFactory.Addr.Builder.class);
    }

    public static final int CONTRY_FIELD_NUMBER = 1;
    private volatile java.lang.Object contry_;
    /**
     * <code>optional string contry = 1;</code>
     */
    public java.lang.String getContry() {
      java.lang.Object ref = contry_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contry_ = s;
        return s;
      }
    }
    /**
     * <code>optional string contry = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContryBytes() {
      java.lang.Object ref = contry_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contry_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 2;
    private volatile java.lang.Object city_;
    /**
     * <code>optional string city = 2;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>optional string city = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getContryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, contry_);
      }
      if (!getCityBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, city_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getContryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, contry_);
      }
      if (!getCityBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, city_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dapper.rpc.serializer.protobuf.PersonFactory.Addr)) {
        return super.equals(obj);
      }
      com.dapper.rpc.serializer.protobuf.PersonFactory.Addr other = (com.dapper.rpc.serializer.protobuf.PersonFactory.Addr) obj;

      boolean result = true;
      result = result && getContry()
          .equals(other.getContry());
      result = result && getCity()
          .equals(other.getCity());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CONTRY_FIELD_NUMBER;
      hash = (53 * hash) + getContry().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dapper.rpc.serializer.protobuf.PersonFactory.Addr parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dapper.rpc.serializer.protobuf.PersonFactory.Addr parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dapper.rpc.serializer.protobuf.PersonFactory.Addr parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dapper.rpc.serializer.protobuf.PersonFactory.Addr parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dapper.rpc.serializer.protobuf.PersonFactory.Addr parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dapper.rpc.serializer.protobuf.PersonFactory.Addr parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dapper.rpc.serializer.protobuf.PersonFactory.Addr parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dapper.rpc.serializer.protobuf.PersonFactory.Addr parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dapper.rpc.serializer.protobuf.PersonFactory.Addr parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dapper.rpc.serializer.protobuf.PersonFactory.Addr parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dapper.rpc.serializer.protobuf.PersonFactory.Addr prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Addr}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Addr)
        com.dapper.rpc.serializer.protobuf.PersonFactory.AddrOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dapper.rpc.serializer.protobuf.PersonFactory.internal_static_Addr_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dapper.rpc.serializer.protobuf.PersonFactory.internal_static_Addr_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dapper.rpc.serializer.protobuf.PersonFactory.Addr.class, com.dapper.rpc.serializer.protobuf.PersonFactory.Addr.Builder.class);
      }

      // Construct using com.dapper.rpc.serializer.proto.PersonFactory.Addr.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        contry_ = "";

        city_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dapper.rpc.serializer.protobuf.PersonFactory.internal_static_Addr_descriptor;
      }

      public com.dapper.rpc.serializer.protobuf.PersonFactory.Addr getDefaultInstanceForType() {
        return com.dapper.rpc.serializer.protobuf.PersonFactory.Addr.getDefaultInstance();
      }

      public com.dapper.rpc.serializer.protobuf.PersonFactory.Addr build() {
        com.dapper.rpc.serializer.protobuf.PersonFactory.Addr result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dapper.rpc.serializer.protobuf.PersonFactory.Addr buildPartial() {
        com.dapper.rpc.serializer.protobuf.PersonFactory.Addr result = new com.dapper.rpc.serializer.protobuf.PersonFactory.Addr(this);
        result.contry_ = contry_;
        result.city_ = city_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dapper.rpc.serializer.protobuf.PersonFactory.Addr) {
          return mergeFrom((com.dapper.rpc.serializer.protobuf.PersonFactory.Addr)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dapper.rpc.serializer.protobuf.PersonFactory.Addr other) {
        if (other == com.dapper.rpc.serializer.protobuf.PersonFactory.Addr.getDefaultInstance()) return this;
        if (!other.getContry().isEmpty()) {
          contry_ = other.contry_;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dapper.rpc.serializer.protobuf.PersonFactory.Addr parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dapper.rpc.serializer.protobuf.PersonFactory.Addr) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object contry_ = "";
      /**
       * <code>optional string contry = 1;</code>
       */
      public java.lang.String getContry() {
        java.lang.Object ref = contry_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contry_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string contry = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContryBytes() {
        java.lang.Object ref = contry_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contry_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string contry = 1;</code>
       */
      public Builder setContry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contry_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string contry = 1;</code>
       */
      public Builder clearContry() {
        
        contry_ = getDefaultInstance().getContry();
        onChanged();
        return this;
      }
      /**
       * <code>optional string contry = 1;</code>
       */
      public Builder setContryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        contry_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>optional string city = 2;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string city = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string city = 2;</code>
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string city = 2;</code>
       */
      public Builder clearCity() {
        
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>optional string city = 2;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        city_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Addr)
    }

    // @@protoc_insertion_point(class_scope:Addr)
    private static final com.dapper.rpc.serializer.protobuf.PersonFactory.Addr DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dapper.rpc.serializer.protobuf.PersonFactory.Addr();
    }

    public static com.dapper.rpc.serializer.protobuf.PersonFactory.Addr getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Addr>
        PARSER = new com.google.protobuf.AbstractParser<Addr>() {
      public Addr parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Addr(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Addr> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Addr> getParserForType() {
      return PARSER;
    }

    public com.dapper.rpc.serializer.protobuf.PersonFactory.Addr getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Addr_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Addr_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\"D\n\006Person\022\n\n\002id\030\001 \001(\005\022\014\n\004" +
      "name\030\002 \001(\t\022\013\n\003age\030\003 \001(\005\022\023\n\004addr\030\004 \001(\0132\005." +
      "Addr\"$\n\004Addr\022\016\n\006contry\030\001 \001(\t\022\014\n\004city\030\002 \001" +
      "(\tB0\n\037com.dapper.rpc.serializer.protoB\rP" +
      "ersonFactoryb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Person_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", "Addr", });
    internal_static_Addr_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Addr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Addr_descriptor,
        new java.lang.String[] { "Contry", "City", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
